### ISSUE TITLE
MS간 연결 방향 관련 

### ISSUE THREAD

**Issue by lunker** [433Project/ConfigServer#1]
config server로 부터 ms들의 정보를 받은 후 
모든 ms들은 10000에 listen 중이다.
누가 connect를 시도할 것인가?

**Comment by Simhyejin** [comment]
config server는 새로 접속한 ms에게 기존 접속한 ms 정보를 알려줍니다.

새로운 ms A가 config server에 접속하고 config sever로 부터 ms들의 ip list를 받는다. 
ms(A)가 conf Server로 부터 받은 모든 서버 ip에 connect를 시도한다.

ms간 연결 방향은 이렇게 하려고 생각했는 데
어떻게 생각하나요?

**Comment by lunker** [comment]
괜찮은듯!
